name: Build-Publish

on:
  push:
    paths: ['.env', 'Dockerfile', 'rootfs/**', 'patches/**']
  workflow_dispatch:
    inputs:
      no-cache:
        description: 'Disable cache'
        required: false
        default: false
        type: boolean

jobs:
  build:
    uses: fabricionaweb/docker-workflows/.github/workflows/build.yml@main
    secrets: inherit
    with:
      no-cache: ${{ inputs.no-cache == 'true' }}
