name: Commit-Upgrade

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to apply to .env (use numbers only)'
        required: true
        type: string

jobs:
  upgrade:
    uses: fabricionaweb/docker-workflows/.github/workflows/upgrade.yml@main
    secrets: inherit
    with:
      version: ${{ inputs.version }}
